name: Sync Issue Labels to PR
on:
  pull_request:
    types: [opened, edited]

jobs:
  sync-labels:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Sync Labels
        uses: actions/github-script@v7
        with:
          script: |
            const pr = context.payload.pull_request
            const body = pr.body
            const issueNumber = body.match(/#(\d+)/)?.[1]
            if (!issueNumber) return

            const issueLabels = await github.rest.issues.listLabelsOnIssue({
              ...context.repo,
              issue_number: issueNumber
            })

            for (const label of issueLabels.data) {
              await github.rest.issues.addLabels({
                ...context.repo,
                issue_number: pr.number,
                labels: [label.name]
              })
            }
